### ISSUE TITLE
Upload not working

### ISSUE THREAD

**Issue by superxtc** [billyhulbert/xbcsmgr#1]
I can download saves just fine witch is great for backups but the upload isn't working for me. Is it broken or is it an issue on my end and how can I fix it?
Thank you!

**Comment by billynothingelse** [comment]
Hi there!

If this is for an Xbox-only title, as such, then unfortunately it will not work. This used to work but it seems Microsoft fixed the issue. You would require using a token captured from a retail console to replace it/upload an overwrite an existing save.

Sorry for that! I may look at it in the future to help with that.
