### ISSUE TITLE
Upload button not working

### ISSUE THREAD

**Issue by jezza3814** [billyhulbert/xbcsmgr#4]
The upload button doesnt actually upload anything. to test it out uploading a bigger file size then downloading and comparing with the smaller size file the program downloads the old file not the newly uploaded one. unless im doing something wrong

**Comment by billynothingelse** [comment]
I stopped working on the project and never fully carried everything over - so it's likely missing. I'm not likely to work on this any time soon so it's an open feature for others to implement.
